{% set name = "pymedphys" %}
{% set version = "0.2.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "24acb064e147efc666dff21f4b281eaf462a6199b7464f55dcd5b67442dba1e9" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - matplotlib
    - attrs
    - pymssql
    - keyring
    - shapely
    - pydicom
    - python-dateutil

test:
  imports:
    - pymedphys
    - pymedphys.dcm
    - pymedphys.electronfactors
    - pymedphys.film
    - pymedphys.geometry
    - pymedphys.logfile
    - pymedphys.msq
    - pymedphys.mudensity
    - pymedphys.plt
    - pymedphys.trf
    - pymedphys.utilities

about:
  home: https://gitlab.com/CCA-Physics/pymedphys
  license: GNU Affero General Public v3 or later (AGPL-3.0+)
  license_family: AGPL
  license_file: LICENSE
  summary: Medical Physics Python toolbox

extra:
  recipe-maintainers:
    - SimonBiggs
