travis:
  secure:
    BINSTAR_TOKEN: Z6iRkL3oojcuFLU1x3fJeTdGtmb5nkK7v6ez0DrNr9aDwK1inCOwq9SZc6WPMzBjP4jJgIzRddY4/bga7KYT4v22ipI5RW9PVlqdkpONCeIMgtFWNJM1SlFadWeJ4tFZP4h7wlsGeQrbqr9X7OP3oACZl3eAP+o3kxEWIf+MdGvIxOwgs6aW7ytvxwX/6fhTK8c6/NmzOSilkFU7eNJJT+IKRhdhLOs/ihBeWzJ09l1fMYLjy2D4F2RTpeUdKPsZk3ZOBR1TSvKrkF8tNyfUHkObP3Gu6+cJdqS9zZQ0KQxsCBuTSorPgXcpEO4GxCnoby/T4csgfeEuxu6VpELY7PX5Wj3qvmkKMQM+ZzpZSBWh+iXRPczM5AzwkBjS0egtNzX2mxpxjBlWNn+PyYdwVgi3vtdl11HEbxCpZwMko0MW+FGBjFWLeSk+QRZ341j0pe8cKv7TpiVjN/KI1sSHUb4IyVjCjytJubpwfPumsktcAGNruI5bl1z0XXFFaFa1iS+3cMfyEYR1WAMqToOlXtchtcWQWU5A8713adYM/Uf5RgM82dtC1UTP8ysVqUVk6gxFTeyh+Z2wUVhUQQdJCOU1JVk9ow1dCGtQFk6cyoLyWoci+L55XwWvhJZg3nZXdEy4T7f+/KERvbqWobJsuYyDT8R0DLfE9gWjQD0abkg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
